name: flutter_libphonenumber_android_example
description: Demonstrates how to use the flutter_libphonenumber_android plugin.
publish_to: none

environment:
  sdk: ^3.9.2
  flutter: ">=3.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  flutter_libphonenumber_android:
    path: ../
  flutter_libphonenumber_platform_interface: ^2.1.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
