name: flutter_libphonenumber_workspace
description: The workspace containing all of the flutter_libphonenumber packages.

environment:
  sdk: ">=3.5.0 <4.0.0"

dev_dependencies:
  flutter_lints: ^6.0.0
