name: flutter_libphonenumber_web
description: Web implementation of the flutter_libphonenumber plugin.
repository: https://github.com/acoutts/flutter_libphonenumber/tree/main/packages/flutter_libphonenumber_web
issue_tracker: https://github.com/acoutts/flutter_libphonenumber/issues
version: 1.3.0

environment:
  sdk: ^3.9.2
  flutter: ">=3.0.0"

resolution: workspace

flutter:
  plugin:
    implements: flutter_libphonenumber
    platforms:
      web:
        pluginClass: FlutterLibphonenumberPlugin
        fileName: flutter_libphonenumber_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_libphonenumber_platform_interface: ^2.1.0
  
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
