name: flutter_libphonenumber
description: Leverages libphonenumber to allow for asynchronous and synchronous formatting of phone numbers in Flutter apps.
repository: https://github.com/sonahcmus/flutter_libphonenumber/tree/main/packages/flutter_libphonenumber
issue_tracker: https://github.com/sonahcmus/flutter_libphonenumber/issues
version: 2.7.1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.0.0"


flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_libphonenumber_android
      ios:
        default_package: flutter_libphonenumber_darwin
      web:
        default_package: flutter_libphonenumber_web
      # linux:
      #   default_package: flutter_libphonenumber_linux
      macos:
        default_package: flutter_libphonenumber_darwin
      # windows:
      #   default_package: flutter_libphonenumber_windows

dependencies:
  flutter:
    sdk: flutter
  flutter_libphonenumber_android:
    path: ../flutter_libphonenumber_android
  flutter_libphonenumber_darwin:
    path: ../flutter_libphonenumber_darwin
  flutter_libphonenumber_platform_interface:
    path: ../flutter_libphonenumber_platform_interface
  flutter_libphonenumber_web:
    path: ../flutter_libphonenumber_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
