name: flutter_libphonenumber
description: Leverages libphonenumber to allow for asynchronous and synchronous formatting of phone numbers in Flutter apps.
repository: https://github.com/acoutts/flutter_libphonenumber/tree/main/packages/flutter_libphonenumber
issue_tracker: https://github.com/acoutts/flutter_libphonenumber/issues
version: 2.7.0

environment:
  sdk: ^3.9.2
  flutter: ">=3.0.0"

resolution: workspace

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_libphonenumber_android
      ios:
        default_package: flutter_libphonenumber_darwin
      web:
        default_package: flutter_libphonenumber_web
      # linux:
      #   default_package: flutter_libphonenumber_linux
      macos:
        default_package: flutter_libphonenumber_darwin
      # windows:
      #   default_package: flutter_libphonenumber_windows

dependencies:
  flutter:
    sdk: flutter
  flutter_libphonenumber_android: ^2.0.0
  flutter_libphonenumber_darwin: ^2.1.0
  flutter_libphonenumber_platform_interface: ^2.1.0
  flutter_libphonenumber_web: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
