name: flutter_libphonenumber_platform_interface
description: A common platform interface for the flutter_libphonenumber plugin.
repository: https://github.com/acoutts/flutter_libphonenumber/tree/main/packages/flutter_libphonenumber_platform_interface
issue_tracker: https://github.com/acoutts/flutter_libphonenumber/issues
version: 2.1.0

environment:
  sdk: ^3.9.2
  flutter: ">=3.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
