name: flutter_libphonenumber_android
description: Android implementation of the flutter_libphonenumber plugin.
repository: https://github.com/sonahcmus/flutter_libphonenumber/tree/main/packages/flutter_libphonenumber_android
issue_tracker: https://github.com/sonahcmus/flutter_libphonenumber/issues
version: 2.0.1

environment:
  sdk: ^3.9.2
  flutter: ">=3.0.0"

resolution: workspace

flutter:
  plugin:
    implements: flutter_libphonenumber
    platforms:
      android:
        package: com.couttsconsulting.flutter_libphonenumber
        pluginClass: FlutterLibphonenumberPlugin
        dartPluginClass: FlutterLibphonenumberAndroid

dependencies:
  flutter:
    sdk: flutter
  flutter_libphonenumber_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
